export const site = {
  doctor: {
    name: 'Dr. Vaidik Chauhan',
    shortName: 'Dr. Vaidik Chauhan',
    degrees: 'MS (ENT), MBBS',
    title: 'MS (ENT) — Consultant ENT Surgeon',
    designation: 'Director & Head, Department of ENT',
    hospitalName: 'Atulya Superspeciality Hospital & ICU, Ahmedabad',
    role: 'Consultant Ear, Nose & Throat Surgeon',
    experienceYears: '10+',
    totalSurgeries: '6,000+',
    publicationsCount: '14+',
    phoneDisplay: '+91 9601074848',
    phoneHref: 'tel:+919601074848',
    email: 'drvc2527@gmail.com',
    specialties: ['Otology', 'Rhinology', 'Skull Base Surgery', 'Endoscopic Sinus Surgery (FESS)', 'Tympanoplasty'],
  },
  hospital: {
    name: 'Atulya Superspeciality Hospital & ICU',
    location: 'Ahmedabad, Gujarat',
    addressLine1: '2nd Floor, Elite Mangnum, Bhuyangdev Cross Rd',
    addressLine2: 'Vardhmannagar Society, C.P. Nagar-1, Parulnagar Society, Ahmedabad, Gujarat 380061',
    phoneDisplay: '+91 9601074848',
    phoneHref: 'tel:+919601074848',
    landlineDisplay: '09727579000',
    landlineHref: 'tel:+919727579000',
    whatsapp: 'https://wa.me/919601074848?text=Hello%20Dr.%20Vaidik%20Chauhan,%20I%20would%20like%20to%20consult%20for%20an%20ENT%20appointment.',
    email: 'drvc2527@gmail.com',
    mapUrl: 'https://www.google.com/maps?q=Atulya+Superspeciality+Hospital+Bhuyangdev+Ahmedabad&output=embed',
  },
} as const

export const navLinks = [
  { label: 'About Doctor', href: '#about' },
  { label: 'Surgical Milestones', href: '#milestones' },
  { label: 'Services', href: '#services' },
  { label: 'Experience', href: '#experience' },
  { label: 'Publications', href: '#publications' },
  { label: 'Workshops & Training', href: '#workshops' },
  { label: 'Hospital & ICU', href: '#hospital' },
  { label: 'Contact', href: '#contact' },
] as const
